version: '3'
services:
  kafka:
    container_name: kafka
    image: 'bitnami/kafka:3.3.1'
    user: root
    ports:
      - "9192:9092"
      - "9193:9093"
    environment:

      KAFKA_ENABLE_KRAFT: yes # 允许使用kraft，即Kafka替代Zookeeper
      KAFKA_CFG_PROCESS_ROLES: broker,controller # kafka角色，做broker，也要做controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER # 指定供外部使用的控制类请求信息
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093 # 定义kafka服务端socket监听端口
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT # 定义安全协议


      KAFKA_KRAFT_CLUSTER_ID: LelM2dIFQkiUFvXCEcqRWA # 使用Kafka时的集群id，集群内的Kafka都要用这个id做初始化，生成一个UUID即可
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093 # 集群地址

      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_HEAP_OPTS: -Xmx512M -Xms256M # 设置broker最大内存，和初始内存
#      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: false # 禁止自动创建主题
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://:9092 # 定义外网访问地址（宿主机ip地址和端口）
      KAFKA_BROKER_ID: 1 # broker.id，必须唯一z`

    networks:
      mynetwork:
        ipv4_address: 172.16.240.10

  flume:
    container_name: flume
    image: probablyfine/flume
    environment:
      FLUME_AGENT_NAME: docker
    volumes:
      - /Users/sparkle6979l/Mavens/FlinkStu/flink-tes/lampp/logs:/opt/lampp/logs
      - ./config.conf:/opt/flume-config/flume.conf
    networks:
      mynetwork:
        ipv4_address: 172.16.240.11


networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.16.240.0/24
          gateway: 172.16.240.1






